#!/bin/sh
#
# generate_isrs.sh: generates ISR stub assembly invocations and their
# corresponding C declarations for all 256 interrupt vectors.
#
# Usage:
#   ./tools/generate_isrs.sh <isr_gen.c> <isr_gen.inc>
#
# Arguments:
#   isr_gen.c  , path to the generated C source file
#   isr_gen.inc, path to the generated NASM include file
#

set -e

if [ $# -lt 2 ]; then
    echo "Usage: generate_isrs.sh <isr_gen.c> <isr_gen.inc>"
    exit 1
fi

ISR_GEN_C="$1"
ISR_GEN_INC="$2"

# CPU exceptions that push an error code onto the stack.
# all other vectors get a dummy zero pushed instead.
ISRS_WITH_ERROR_CODE="8 10 11 12 13 14 17 21"

# helper: returns 0 (true) if the given vector pushes an error code.
has_error_code()
{
    for code in $ISRS_WITH_ERROR_CODE; do
        if [ "$1" = "$code" ]; then
            return 0
        fi
    done
    return 1
}

# Generate the NASM include file (isr_gen.inc)
echo "; AUTO-GENERATED by tools/generate_isrs.sh, do not edit." > "$ISR_GEN_INC"
echo "" >> "$ISR_GEN_INC"

i=0
while [ "$i" -le 255 ]; do
    if has_error_code "$i"; then
        echo "ISR_ERRORCODE $i" >> "$ISR_GEN_INC"
    else
        echo "ISR_NOERRORCODE $i" >> "$ISR_GEN_INC"
    fi
    i=$((i + 1))
done


# Generate the C source file (isr_gen.c)
cat > "$ISR_GEN_C" <<'HEADER'
/* AUTO-GENERATED by tools/generate_isrs.sh, do not edit. */

#include "idt.h"
#include "gdt.h"

HEADER

# emit extern declarations for all 256 ISR stubs defined in isr.asm
i=0
while [ "$i" -le 255 ]; do
    echo "extern void isr_stub_${i}(void);" >> "$ISR_GEN_C"
    i=$((i + 1))
done

# emit the gate initialization function
cat >> "$ISR_GEN_C" <<'FUNC_OPEN'

/**
 * install all 256 ISR stub handlers into the IDT.
 * called by isr_initialize() during kernel startup.
 */
void isr_init_gates(void)
{
FUNC_OPEN

i=0
while [ "$i" -le 255 ]; do
    # vectors 0-31: CPU exceptions, use trap gates so IF is not cleared on entry.
    # vectors 32+: hardware IRQs and user-defined, use interrupt gates to prevent
    # re-entrant IRQ dispatch while a handler is running.
    if [ "$i" -le 31 ]; then
        gate_type="IDT_FLAG_GATE_32BIT_TRAP"
    else
        gate_type="IDT_FLAG_GATE_32BIT_INT"
    fi
    echo "    idt_set_gate($i, isr_stub_${i}, GDT_CODE_SEGMENT, IDT_FLAG_RING0 | ${gate_type});" >> "$ISR_GEN_C"
    i=$((i + 1))
done

echo "}" >> "$ISR_GEN_C"
